version: '3'
services:
  postgres:
    container_name: galaxy-postgres
    image: postgres:12.2
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=galaxy
      - POSTGRES_USER=galaxy
    restart: always
